services:
    code_mirror.asset_manager:
        class: Solution\CodeMirrorBundle\Asset\AssetManager
        arguments: ["@file_locator", '%code_mirror.mode_dirs%', '%code_mirror.themes_dirs%',  '%kernel.cache_dir%', '%kernel.environment%']

    Solution\CodeMirrorBundle\Form\Type\CodeMirrorType:
        arguments: ['%code_mirror.parameters%']
        tags:
            - { name: form.type }

    code_mirror.twig.extension:
        class: Solution\CodeMirrorBundle\Twig\CodeMirrorExtension
        arguments: ["@code_mirror.asset_manager"]
        tags:
            - { name: twig.extension }
