services:
    code_mirror.asset_manager:
        class: Solution\CodeMirrorBundle\Asset\AssetManager
        arguments: ["@file_locator", %code_mirror.mode_dirs%, %code_mirror.themes_dirs%, %code_mirror.addons_dirs%, %kernel.cache_dir%, %kernel.environment%]

    code_mirror.form.type:
        class: %code_mirror.form_type%
        arguments: [%code_mirror.parameters%]
        tags:
            - { name: form.type, alias: code_mirror }

    code_mirror.twig.extension:
        class: Solution\CodeMirrorBundle\Twig\CodeMirrorExtension
        arguments: ["@code_mirror.asset_manager"]
        tags:
            - { name: twig.extension }
